### ISSUE TITLE
Deprecation Notice on PSR-0

### ISSUE THREAD

**Issue by whyte624** [GenesisGateway/genesis_php#12]
Deprecation Notice: Class Genesis\Api\Constants\BankAccountTypes located in ./vendor/genesisgateway/genesis_php/src/Genesis/API/Constants/BankAccountTypes.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0.

**Comment by whyte624** [comment]
Please, consider merging this pull request:

https://github.com/GenesisGateway/genesis_php/pull/11

**Comment by dyd** [comment]
Fixed [here](https://github.com/GenesisGateway/genesis_php/releases/tag/1.18.6)
