### ISSUE TITLE
Unknown error during network request!

### ISSUE THREAD

**Issue by sanoopksanu** [GenesisGateway/genesis_php#15]
We are facing a challenges on integrating the API, We are using library downloaded from URL https://github.com/GenesisGateway/genesis_php.

  We have configured it using provided username and password. But we get some error while calling API 
error 

Unknown error during network request!

Notice: Undefined offset: 1 in C:\xampp\htdocs\trawex\genesis\genesis_php-master\src\Genesis\Network\cURL.php on line 120

Warning: XMLReader::XML(): Empty string supplied as input in C:\xampp\htdocs\trawex\genesis\genesis_php-master\src\Genesis\Parsers\XML.php on line 90

Warning: XMLReader::read(): Load Data before trying to read in C:\xampp\htdocs\trawex\genesis\genesis_php-master\src\Genesis\Parsers\XML.php on line 93

Warning: XMLReader::read(): Load Data before trying to read in C:\xampp\htdocs\trawex\genesis\genesis_php-master\src\Genesis\Parsers\XML.php on line 116

**Comment by dyd** [comment]
Hello @sanoopksanu,
This is most likely a configuration issue. May I ask you to describe your issue and send us a request to tech-support@emerchantpay.com

I think that already our colleagues are working on your case if not just send us an e-mail.
