### ISSUE TITLE
Unknown transaction status "submitted"

### ISSUE THREAD

**Issue by Tklaversma** [GenesisGateway/genesis_php#16]
Since yesterday, whenever we try to get a transaction, we get the error that the API received an unknown transaction status `submitted`, which is true, since this status does not exist in `Genesis\API\Constants\Transaction\States`.

Below the code we use:
```php
    public function getPayment(string $transactionId): array
    {
        $data = [];

        try {
            $genesis = new Genesis('WPF\Reconcile');
            $request = $genesis->request();

            $request->setUniqueId($transactionId);
            $genesis->execute(); // !!! THIS GIVES THE ERROR
            $response = $genesis->response()->getResponseObject();

            $data = json_decode(json_encode($response), true);
        } catch (Exception $e) {
            $this->errorLogger($e, null, true);
        }

        return $data;
    }
```

The function `execute()` calls `$this->responseCtx->parseResponse()` which checks if the received state is valid `$state->isValid()`. If not, then an error is thrown. And since `$this->responseObj->status` is `submitted`, it does.

What am I missing? This package has been working for years now.. and we update regularly.

Awaiting your response. 

P.S.: We use the latest version of this package.

**Comment by dyd** [comment]
Hello @Tklaversma,

Thank you for the reported issue. We will check it.

**Comment by Tklaversma** [comment]
@dyd Any update?

**Comment by dyd** [comment]
Hello @Tklaversma,

We have a new version:

<a href="https://github.com/GenesisGateway/genesis_php/releases/tag/1.21.3">GitHub Tag 1.21.3</a>
<a href="https://packagist.org/packages/genesisgateway/genesis_php">Genesis PHP via Packagist</a>

Transaction States were updated, and the Response object should be parsed properly.

If you have any issues, let us know. Closing this one.

**Comment by Tklaversma** [comment]
@dyd Could you tell me what the status `submitted` means? Is it a final status like `approved` or an initial status like `pending`? Reason I'm asking, is that we still have 3 transactions on `submitted` not knowing what to do...

**Comment by dyd** [comment]
@Tklaversma You better contact tech-support@emerchantpay.com. I see that you have a response in the official ticket.

Anyway, the submitted status indicates that the Web Payment Form has been submitted by the user/customer.

**Comment by RoodFruit** [comment]
@dyd I got the answer via mail already. Thanks.

> the submitted status indicates that the Web Payment Form has been submitted by the user/customer

Furthermore, you are wrong about the state `submitted`. Submitted, apparently, is a final state that can be handled like `failed`.

**Comment by dyd** [comment]
@RoodFruit I could be wrong, but `submitted` should not be final. `submitted` indicates that the Web Payment Form was `submitted` (clicked Pay button). It is last in terms of the action of WPF submission.

After submitting the WPF, you will receive a notification with the `Approved|Error|Declined` status upon the actual payment. I don't think that submitted should be considered a failed payment. The payment status is one of `Approved|Error|Declined|Refunded|Voided` in terms of "final payment status"

You better ask tech-support@emerchantpay.com if you have any concerns or issues with the payment flow.

**Comment by Tklaversma** [comment]
@dyd thats exactly what I did, and they told me this. When their api returns "submitted", we should consider it as "failed".

**Comment by Tklaversma** [comment]
@dyd I think you are right about what submitted means, but not about when this status is given by their API.
