### ISSUE TITLE
There is a way to get Raw request as string Xml format?

### ISSUE THREAD

**Issue by muratsplat** [GenesisGateway/genesis_php#2]
We want to save raw request when each transaction sends request to e-comprocessing.net .

**Comment by dimitrovv** [comment]
Hi, 

you can use this method 

`$xmlRequest = $genesis->request()->getDocument();`

to retrieve the request as XML Format. You could simply call this method just before 
`$genesis->execute();`

The Request XML will look like this if you send a transaction according to our example in section 
**Getting Started**

`<?xml version="1.0" encoding="UTF-8"?>
<payment_transaction>
  <transaction_type>authorize</transaction_type>
  <transaction_id>43671</transaction_id>
  <usage>40208 concert tickets</usage>
  <remote_ip>245.253.2.12</remote_ip>
  <amount>5000</amount>
  <currency>USD</currency>
  <card_holder>Emil Example</card_holder>
  <card_number>4200000000000000</card_number>
  <cvv>123</cvv>
  <expiration_month>01</expiration_month>
  <expiration_year>2020</expiration_year>
  <customer_email>emil@example.com</customer_email>
  <customer_phone>1987987987987</customer_phone>
  <billing_address>
    <first_name>Travis</first_name>
    <last_name>Pastrana</last_name>
    <address1>Muster Str. 12</address1>
    <zip_code>10178</zip_code>
    <city>Los Angeles</city>
    <state>CA</state>
    <country>US</country>
  </billing_address>
</payment_transaction>`

**Best Regards**,
Ventsislav Dimitrov

**Comment by muratsplat** [comment]
@dimitrovv  Thanks.
