### ISSUE TITLE
BirthDate parameter is missing ... 

### ISSUE THREAD

**Issue by muratsplat** [GenesisGateway/genesis_php#4]

**Comment by dimitrovv** [comment]
Hi Murat,

your terminal is not configured properly and that's why you receive this error message from the payment gateway.

We are going to setup the terminal correctly and will inform you when it is ready.
You should not pass an additional parameter for the Birth Date.

Best Regards,
Ventsislav Dimitrov

**Comment by muratsplat** [comment]
We will use 6012 Mcc code for our transactions.

**Comment by muratsplat** [comment]
Gateway returns : "errors: Birth date InputDataMissingError: 'birth_date' is missing"

**Comment by dimitrovv** [comment]
Hi Murat,

the Birth Date parameter must be passed to the request in a different way.
We are going to update our SDK and will inform you when you can update it to the latest version.

Currently our SDK does not support the newest updates with this Birth Date parameter.

We plan to update the library in the next days.

Best Regards,
Ventsislav Dimitrov

**Comment by muratsplat** [comment]
You can explain " a different way." ? If the way save the time for us, It is able to try to it..

Our system is implemented to Genesis via this sdk. If we resolved birth_date param issue we want live credential from your corp. we look forward to the update about  birth_date...

**Comment by dimitrovv** [comment]
Hi,

we have updated our SDK to allow passing the additional parameter `birth_date`.

You can use the following code to set the Birth Date to the following Processing APIs:
- Financial
  - **Authorize**
  - **Authorize3D**
  - **InitRecurringSale**
  - **InitRecurringSale3D**
  - **PayByVouchers Sale**
  - **Payout**
  - **Sale**
  - **Sale3D**
- NonFinancial
  - **AccountVerification**
  - **AVS**

``` php
<?php
    $genesis
        ->request
             ->setBirthDate( "23-08-1977" ); //format "dd-mm-yyyy"
?>
```

Best Regards,
Ventsislav Dimitrov

**Comment by muratsplat** [comment]
Thanks @dimitrovv 
I will try again for success transaction on your test env with v1.4.3
