### ISSUE TITLE
Genesis throws this exception  -> \Genesis\Exceptions\ErrorNetwork

### ISSUE THREAD

**Issue by muratsplat** [GenesisGateway/genesis_php#7]
Raw Request:
 <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<reconcile>\n  <transaction_id>4660-1465834496-88-118</transaction_id>\n</reconcile>\
Code:3
Message:Illegal characters found in URL

Sdk throws exception that on the title, but in Genesis Merchant Console  it looks  the transaction is passed on success. 

We have sent "Financial\Cards\Authorize3D" and after then "NonFinancial\Reconcile\Transaction" requests.

**Comment by muratsplat** [comment]
Why  did you set invalid the issue?

**Comment by dimitrovv** [comment]
Hi Murat,

your Request XML 

``` xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n 4660-1465834496-88-118\n\
```

is invalid.

You can use 

``` php
\Genesis\API\Notification
```

to handle a notification from the Gateway and it will automatically create a Reconcile Transaction.
You can find more information [here](https://github.com/GenesisGateway/genesis_php#notifications) about how you can use this class. This `API\Notification` handler must be implemented in your Notification Controller (Notification URL)

We have mentioned a lot invalid Reconcile Attempts, that you have sent to the gateway.
Ex.

``` xml
<?xml version="1.0" encoding="UTF-8"?> <reconcile> <transaction_id>575ecdd525d39</transaction_id> </reconcile>
```

Here is an example of the Raw Request for your transaction

``` xml
<?xml version="1.0" encoding="UTF-8"?> 
<reconcile> 
      <transaction_id>4660-1465834496-88-118</transaction_id> 
</reconcile>
```

Example PHP Code:

``` php
$genesis = new \Genesis\Genesis('NonFinancial\Reconcile\Transaction');

try {
    $genesis
        ->request()
            ->setTransactionId('4660-1465834496-88-118');

    /*
    //you can send also a Reconcile Transaction using the Unique Id of the Authorized 3D Transaction 
    $genesis
        ->request()
            ->setUniqueId('UNIQUE_ID_HERE');
    */

    $requestXML = $genesis->request()->getDocument();
    /*$requestXML => <?xml version="1.0" encoding="UTF-8"?> <reconcile> <transaction_id>4660-1465834496-88-118</transaction_id> </reconcile>*/

    $genesis->execute();

    $reconciliationObj = $genesis->response()->getResponseObject();
} catch (\Genesis\Exceptions\ErrorAPI $api) {
    // This is reconciliation, don't throw on ErrorAPI
}
```

Best Regards,
Ventsislav Dimitrov

**Comment by muratsplat** [comment]
Hello Ventsislav,

We have set wrong value token using Genesis SDK. We are used Raw request as token, the sdk  merged url endpoint and raw request. That causes invalid url. 

I'm sorry for wrong alert :confounded: :pray:
